name: Perform Test

on:
  push:
    branches: [main]

jobs:
  run-test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Inject Test Environment Variables
        run: |
          touch .env.test
          echo '${{ secrets.ENV_FILE }}'' >> .env.test

      - name: Test ENV
        run: |
          echo '${{ secrets.ENV_FILE }}'

      - name: Run Tests
        run: npm run test
